export const PREDEFINED_INCOME = [
  'Salary',
  'Freelance',
  'Investments',
  'Rental Income',
  'Business',
  'Pension',
  'Child Support',
  'Government Benefits',
  'Other Income',
]

export const PREDEFINED_EXPENSES = [
  'Rent / Mortgage',
  'Groceries',
  'Utilities',
  'Transportation',
  'Car Payment',
  'Car Insurance',
  'Health Insurance',
  'Healthcare',
  'Dining Out',
  'Entertainment',
  'Subscriptions',
  'Phone',
  'Internet',
  'Clothing',
  'Education',
  'Childcare',
  'Gym',
  'Travel',
  'Savings',
  'Gifts',
  'Personal Care',
  'Home Maintenance',
  'Pets',
  'Other',
]
